In [1]:
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 4.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [2]:
import spacy
import numpy as np
import pandas as pd

In [3]:
nlp = spacy.load("en_core_web_lg")

In [4]:
print('Vector Size : ', nlp.vocab.vectors['book'].shape)
print('Word ID     : ', nlp.vocab.strings['book'])

Vector Size :  (300,)
Word ID     :  13814433107111459297


In [5]:
most_similar = nlp.vocab.vectors.most_similar(np.asarray([nlp.vocab.vectors[nlp.vocab.strings['delhi']]]), n = 10)



In [6]:
most_similar

(array([[ 5921900950848012081, 14866201730363328710,  6193280578997606245,
         10728978622862958968,  6180816728799703956, 16337805628567794723,
         17383155000740340679,  7057732381406613485, 17230512040027004388,
         10881106343428755787]], dtype=uint64),
 array([[ 23462,  18721, 153570,  59447, 142848,  94736, 135983,   1723,
         154081,  22545]], dtype=int32),
 array([[1.    , 0.8714, 0.8423, 0.8234, 0.7989, 0.793 , 0.7858, 0.7856,
         0.7404, 0.7396]], dtype=float32))

In [7]:
for word in most_similar[0][0]:
  print(nlp.vocab.strings[word].center(20))

       DELHI        
       MUMBAI       
     BANGALORE      
      chennai       
        PUNE        
     HYDERABAD      
      kolkata       
       INDIA        
     CHANDIGARH     
       JAIPUR       


In [8]:
doc1 = nlp('Earth is a planet')
doc2 = nlp('Mars in red')

similarity_score = doc1.similarity(doc2)
print(similarity_score)


0.5398212671279907


In [10]:
text=nlp('sun rises in the east wowwww')

data=pd.DataFrame([(token.text, token.has_vector, token.is_oov) for token in text],
    columns=['Token', 'Vector', 'OOV'])

In [11]:
data

Token  Vector    OOV
0     sun    True  False
1   rises    True  False
2      in    True  False
3     the    True  False
4    east    True  False
5  wowwww    True  False